DROP TABLE IF EXISTS tblEventVinna;
DROP TABLE IF EXISTS tblWorks;
DROP TABLE IF EXISTS tblOrder;
DROP TABLE IF EXISTS tblAsk;

DROP TABLE IF EXISTS tblInterpreter;
DROP TABLE IF EXISTS tblProject;
DROP TABLE IF EXISTS tblCustom;
DROP TABLE IF EXISTS tblBeidni;
DROP TABLE IF EXISTS tblEventTable;
DROP TABLE IF EXISTS tblUsers;

DROP TABLE IF EXISTS tblStudent;
DROP TABLE IF EXISTS tblKennslutima;